#!/bin/bash
#/etc/init.d/gogs-service
#

### BEGIN INIT INFO
# Provides:          gogs-service
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Gogs service
# Description:       init.d script for Gogs service
### END INIT INFO

# XXX - edit these
GOGS_DIR="/home/pi/srcs/go/src/github.com/gogits/gogs"
GOGS_USER="pi"

GOGS_USER_HOME="/home/$GOGS_USER"
GOGS_START_SCRIPT="$GOGS_DIR/start.sh"
GOGS_LOG_DIR="$GOGS_DIR/log"

start_gogs() {
  echo "Starting gogs..."
  su - $GOGS_USER -c "nohup $GOGS_START_SCRIPT > $GOGS_LOG_DIR/gogs.log 2>&1 &"
}

# Gogs needs a home path.
export HOME=$GOGS_USER_HOME

# commands
case "$1" in
  start)
    ps aux | grep 'gogs' | grep -v grep | grep -vq start
    if [ $? = 0 ]; then
      echo "Gogs is already running."
    else
      start_gogs
    fi
    ;;
  stop)
    ps aux | grep 'gogs' | grep -v grep | grep -vq stop
    if [ $? = 0 ]; then
      echo "Stopping Gogs."
      kill `ps -ef | grep 'gogs' | grep -v grep | awk '{print $2}'`
    else
      echo "Gogs is already stopped."
    fi
    ;;
  restart)
    ps aux | grep 'gogs' | grep -v grep | grep -vq restart
    if [ $? = 0 ]; then
      kill `ps -ef | grep 'gogs' | grep -v grep | awk '{print $2}'`
    fi
    start_gogs
    ;;
  status)
    ps aux | grep 'gogs' | grep -v grep | grep -vq status
    if [ $? = 0 ]; then
      echo "Gogs is running."
    else
      echo "Gogs is stopped."
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/gogs-service {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
#!/bin/bash
#/etc/init.d/gogs-service
#

### BEGIN INIT INFO
# Provides:          gogs-service
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Gogs service
# Description:       init.d script for Gogs service
### END INIT INFO

# XXX - edit these
GOGS_DIR="/home/pi/srcs/go/src/github.com/gogits/gogs"
GOGS_USER="pi"

GOGS_USER_HOME="/home/$GOGS_USER"
GOGS_START_SCRIPT="$GOGS_DIR/start.sh"
GOGS_LOG_DIR="$GOGS_DIR/log"

start_gogs() {
  echo "Starting gogs..."
  su - $GOGS_USER -c "nohup $GOGS_START_SCRIPT > $GOGS_LOG_DIR/gogs.log 2>&1 &"
}

# Gogs needs a home path.
export HOME=$GOGS_USER_HOME

# commands
case "$1" in
  start)
    ps aux | grep 'gogs' | grep -v grep | grep -vq start
    if [ $? = 0 ]; then
      echo "Gogs is already running."
    else
      start_gogs
    fi
    ;;
  stop)
    ps aux | grep 'gogs' | grep -v grep | grep -vq stop
    if [ $? = 0 ]; then
      echo "Stopping Gogs."
      kill `ps -ef | grep 'gogs' | grep -v grep | awk '{print $2}'`
    else
      echo "Gogs is already stopped."
    fi
    ;;
  restart)
    ps aux | grep 'gogs' | grep -v grep | grep -vq restart
    if [ $? = 0 ]; then
      kill `ps -ef | grep 'gogs' | grep -v grep | awk '{print $2}'`
    fi
    start_gogs
    ;;
  status)
    ps aux | grep 'gogs' | grep -v grep | grep -vq status
    if [ $? = 0 ]; then
      echo "Gogs is running."
    else
      echo "Gogs is stopped."
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/gogs-service {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
